sauce_connect: true
loopback: airtap.local
browsers:
  - name: chrome
    version: [45, -1..latest]
  - name: firefox
    version: [38, -1..latest]
  - name: microsoftedge
    version: [13, -1..latest]
  - name: ie
    version: 10..latest
  - name: safari
    version: 9..latest
  - name: iphone
    version: [9.3, latest]
  - name: android
    version: [4.4, latest]
