language: node_js
node_js:
- lts/*
addons:
  sauce_connect: true
  hosts:
  - airtap.local
after_success: npm run coverage
env:
  global:
  - secure: aCnxKAKoMGT6TuvVLBTB056FDe0N7SY6P74hOMTXgdugwSzV6+1/i3DWV5telS8LFEBvIsoSU/3TbMs9c7zyZJTtC1eYWpgeiI+KeoHs3eI52ASS/U0i+RWfcUVNJ7Wiwkj3sHjobD3oirqlz7XUFC6YvIxk3AqJDgC+I/F2hI152JLC51MN28VnsMyKO5prcGKGyrSwf9t9lOXuKA+1kP+l234Ad1uqIgCacHyNblvLJNUzeTxfUXVJp/M6+vHXkjELrU13Mg6fvxwNN+i9irx3WeYfHP+F14tK1GIAViPDAWNLlm8MDCetL4T/bzQ2R9eEe3cIiprdN/EoBkdLXldgsPuThGfhGW3TSx+uy/kKiYnTo5eteLF3U3ZmtBZgdcHyJRgCS9/kc+OgqBuvJPMs3gFhhzKrByK6h+51uCiVdgU7fVUKK2YR/U+F8zY3IZw4ORnhQIEb6hoDXq9Pba9LhHMp+Ze7ZSPHZcb29ShrUoXs7TZiyxIC3FauL5YjiHQwAahuccMeUjtb3yOE/o/75amWtuqD3i/ihszaowZE9JsUwmJorpANzIojnnQxdc67MyZ1Mnwyf3WdPLBIf8IM/WfVNJ5E9ZWwKiy0b/yd1d2nydkDcaHbaPrArK2QSUKRpjIMbje2/RTI03awiBI1V+GvI3TTN8omy3uOFlA=
  - secure: GBnO2af4yUfoYdudl13PibT+LEz+yK3mBa0dRZU+0akq9+7B8rvX5UEKVaWdf0WnFprQTCUZqZU6RNvWSeboThTmmOT1C9qM0kVzikYcjW3EkpEg4p290wvx2ZGHwJ3l8FKTD1Ip9h6IcrgMalq8Y4adlWVdjJsffWKGgTwbnTFgs7Xjauz56FfvhsApBih8xuHv8Q9mQ/Tyx+tCwiE6RursGoDYTEPlZmu2q2Rph7v+M2uZJtUw/+EMAgzu0WtM2AcOwCsRR7r88TI729C3c5mtBil3v172oV7oswiTlAZujCbA2KqRScoFeCz5RoUD9U6ps6De8rIOrXq3/C/0yZmzV/KzUUaYzcer0d+RaH1/ugRQcEOiDn7OoqyGFC01n9J01+j8LWJW0dVBgpdK6ANqyhvij0zre/V6fEqUftP+D4F9kAKR4l6KIOChTy3BUAyOwYx+sssKY6Uo2hBHK4HQokcx0EODq8efdJbLnez52Tr+zsWlQ68JQmrJxxktycDON3DnqMYJ9ID9xID645+7z1A1CtLdQ+8UhpxLVIf1PlcsSjPx6BX0ZQC/9BBCNxlZorimgWzQ+wT7TkF+lKKfYC12zMdUGEvt0HPFEhPT/SEEvcNUD0Hu4YVamJZOYoh6i1kDYcTJ7vkckQZUqr8WiMg5PeXVx6DeqyidK/o=
